apiVersion: v1
kind: Namespace
metadata:
  name: awx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: awx-k8s-admin
  namespace: awx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: awx-k8s-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: awx-k8s-admin
    namespace: awx
